import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		int boys, girls, children;
		double averageChildren = 0;
		int couplesWithTwo = 0, couplesWithThree = 0, couplesWithFourOrMore = 0;
		for (int i=0; i < T; i++){
			boys = girls = 0;
			while(boys <1 || girls <1){
				double rand = generator.nextDouble();
				if(rand < 0.5){
					boys++;
				} 
				else{
					girls++;
				}
			}
			children = boys + girls;
			if ((boys + girls) == 2) couplesWithTwo++;
			if ((boys + girls) == 3) couplesWithThree++;
			if ((boys + girls) >= 4) couplesWithFourOrMore++;	
			averageChildren += children;
		}
			int mostCommon = Math.max(couplesWithTwo,Math.max(couplesWithThree, couplesWithFourOrMore));
			averageChildren /= T;
		System.out.println("Average: " + averageChildren + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + couplesWithTwo);
		System.out.println("Number of families with 3 children: " + couplesWithThree);
		System.out.println("Number of families with 4 or more children: " + couplesWithFourOrMore);
		if (mostCommon == couplesWithTwo) System.out.println("The most common number of children is 2.");
		else if (mostCommon == couplesWithThree) System.out.println("The most common number of children is 3.");
		else System.out.println("The most common number of children is 4 or more.");
	}
}
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	

